name: Enforce Merge Rules

on:
  push:
    branches:
      - main

jobs:
  enforce-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check Merge Source
        run: |
          if ! git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep -q "dev/"; then
            echo "Error: Merges into main are only allowed from the 'dev' branch."
            exit 1
          fi
